name: requestz
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - name: Setup Gyro
        uses: mattnite/setup-gyro@v1
      - run: gyro build test
      - run: zig fmt --check src build.zig
